# Unity Catalog as the single catalog implementation
spark.sql.catalog.datalake_uc=io.unitycatalog.spark.UCSingleCatalog
spark.sql.catalog.datalake_uc.uri=http://unity-catalog-server:8080
spark.sql.catalog.datalake_uc.token=
spark.sql.defaultCatalog=datalake_uc

spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog

spark.jars.packages=io.delta:delta-spark_2.12:3.2.1,org.apache.hadoop:hadoop-aws:3.3.4,org.apache.spark:spark-avro_2.12:3.5.3,io.unitycatalog:unitycatalog-spark_2.12:0.2.1
spark.hadoop.fs.s3a.access.key=accesskey
spark.hadoop.fs.s3a.secret.key=secretkey
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3.endpoint=http://minio:9000
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3.access.key=accesskey
spark.hadoop.fs.s3.secret.key=secretkey
spark.hadoop.fs.s3.path.style.access=true
spark.hadoop.fs.s3.connection.ssl.enabled=false
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.bucket.datalake-landing.access.key=accesskey
spark.hadoop.fs.s3a.bucket.datalake-landing.secret.key=secretkey
spark.hadoop.fs.s3a.bucket.datalake-landing.endpoint=http://minio:9000
spark.hadoop.fs.s3a.bucket.datalake-landing.path.style.access=true
spark.hadoop.fs.s3a.bucket.datalake-landing.connection.ssl.enabled=false
spark.hadoop.fs.s3a.bucket.datalake-bronze.access.key=accesskey
spark.hadoop.fs.s3a.bucket.datalake-bronze.secret.key=secretkey
spark.hadoop.fs.s3a.bucket.datalake-bronze.endpoint=http://minio:9000
spark.hadoop.fs.s3a.bucket.datalake-bronze.path.style.access=true
spark.hadoop.fs.s3a.bucket.datalake-bronze.connection.ssl.enabled=false
spark.hadoop.fs.s3a.bucket.datalake-silver.access.key=accesskey
spark.hadoop.fs.s3a.bucket.datalake-silver.secret.key=secretkey
spark.hadoop.fs.s3a.bucket.datalake-silver.endpoint=http://minio:9000
spark.hadoop.fs.s3a.bucket.datalake-silver.path.style.access=true
spark.hadoop.fs.s3a.bucket.datalake-silver.connection.ssl.enabled=false
spark.hadoop.fs.s3a.bucket.datalake-gold.access.key=accesskey
spark.hadoop.fs.s3a.bucket.datalake-gold.secret.key=secretkey
spark.hadoop.fs.s3a.bucket.datalake-gold.endpoint=http://minio:9000
spark.hadoop.fs.s3a.bucket.datalake-gold.path.style.access=true
spark.hadoop.fs.s3a.bucket.datalake-gold.connection.ssl.enabled=false
spark.hadoop.fs.s3a.bucket.datalake-uc.access.key=accesskey
spark.hadoop.fs.s3a.bucket.datalake-uc.secret.key=secretkey
spark.hadoop.fs.s3a.bucket.datalake-uc.endpoint=http://minio:9000
spark.hadoop.fs.s3a.bucket.datalake-uc.path.style.access=true
spark.hadoop.fs.s3a.bucket.datalake-uc.connection.ssl.enabled=false
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.warehouse.dir=s3://datalake-uc/warehouse