hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://postgres-uc:5432/unity_catalog_db
hibernate.connection.user=uc_admin
hibernate.connection.password=uc_admin
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
