server.env=dev

s3.bucketPath.0=s3://datalake-landing
s3.region.0=us-east-1
s3.accessKey.0=accesskey
s3.secretKey.0=secretkey
s3.sessionToken.0=sessiontoken

s3.bucketPath.1=s3://datalake-bronze
s3.region.1=us-east-1
s3.accessKey.1=accesskey
s3.secretKey.1=secretkey
s3.sessionToken.1=sessiontoken

s3.bucketPath.2=s3://datalake-silver
s3.region.2=us-east-1
s3.accessKey.2=accesskey
s3.secretKey.2=secretkey
s3.sessionToken.2=sessiontoken

s3.bucketPath.3=s3://datalake-uc
s3.region.3=us-east-1
s3.accessKey.3=accesskey
s3.secretKey.3=secretkey
s3.sessionToken.3=sessiontoken

s3.bucketPath.4=s3://datalake-gold
s3.region.4=us-east-1
s3.accessKey.4=accesskey
s3.secretKey.4=secretkey
s3.sessionToken.4=sessiontoken
