version: "3"
services:

  zookeeper: # this is the config manager
    container_name: zookeeper
    hostname: zookeeper
    build:
      context: .
      dockerfile: ./docker/zookeeper/Dockerfile
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -tuln | grep 2181 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nifi-registry:
    build:
      context: .
      dockerfile: ./docker/nifi-registry/Dockerfile
    container_name: nifi-registry
    ports:
      - 19090:19090
    volumes:
      - nifi_registry_data:/opt/nifi-registry/nifi-registry-current
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=19090
    restart: on-failure
    healthcheck:
      test: curl --fail -I http://$(hostname -i || echo localhost):19090/nifi-registry || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  nifi:
    build:
      context: .
      dockerfile: ./docker/nifi/Dockerfile
    container_name: nifi
    depends_on:
      - zookeeper
      - nifi-registry
    volumes:
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository      
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - ./minio_sites:/opt/nifi/nifi-current/minio_sites
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_drivers:/opt/nifi/drivers
    ports:
      - 8443:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      # - NIFI_CLUSTER_IS_NODE=true
      # - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
    restart: always
    healthcheck:
      test: curl --fail -I http://$(hostname -i || echo localhost):8080/nifi || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nifi_conf:
    driver: local
  nifi_database_repository:
    driver: local
  nifi_flowfile_repository:
    driver: local
  nifi_content_repository:
    driver: local
  nifi_provenance_repository:
    driver: local
  nifi_state:
    driver: local
  nifi_logs:
    driver: local
  nifi_registry_data:
    driver: local
  nifi_drivers:
    driver: local

networks:
  default:
    name: data-plataform
    external: true